[pytest]
python_files = Test_*.py test_*.py
python_classes = Test_*
python_functions = test_*
testpaths = tests
markers =
    e2e: testes end-to-end
    login: testes relacionados ao login
    homepage: tests da homepage
    product: testes relacionados à página de produtos
    cart: testes relacionados ao carrinho de compras