[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    login: testes relacionados ao login
    homepage: tests da homepage
    product: testes relacionados à página de produtos
    cart: testes relacionados ao carrinho de compras
    e2e: testes end-to-end